version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
          node-version: "10.17.0"
            - run: npm install
            # for test
            - run: npm test
            # for linter
            - run: npm install eslint 
            - run: npx eslint src/**
workflows:
    build-and-test:
      jobs:
        - build-and-test
